services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-laravel-app:latest
    container_name: laravel_app
    restart: always
    volumes:
      - .:/var/www
    depends_on:
      - mysql

  node:
    image: node:18
    container_name: node_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: sh -c "npm install && npm run build"

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app

volumes:
  mysql_data:
